# i3blocks configuration (adapted from itsfoss.com/i3-customization)

[cpu_usage]
command=/usr/share/i3blocks/cpu_usage
label=
interval=2
color=#a8a3c1
separator_block_width=20

[memory]
command=/usr/share/i3blocks/memory
label=
interval=30
color=#a8a3c1
separator_block_width=20

[disk]
command=/usr/share/i3blocks/disk
label=
interval=30
color=#a8a3c1
separator_block_width=20

[volume]
command=/usr/share/i3blocks/volume
label=
interval=1
signal=10
color=#a8a3c1
separator_block_width=20

[keyboard_layout]
command=~/.config/i3blocks/keyboard_layout
label=🖮
interval=1
color=#a8a3c1
separator_block_width=20

[time]
command=date "+%Y-%m-%d %H:%M:%S"
label=
interval=1
color=#a8a3c1
separator_block_width=20
