unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key H previous-window
bind-key L next-window

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Smart pane switching (vim-aware, no prefix needed)
set -g @plugin 'christoomey/vim-tmux-navigator'
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -n 'C-\ ' if-shell "$is_vim" 'send-keys C-\ ' 'select-pane -l'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @dracula-show-powerline true
set -g @dracula-fixed-location "TLV"
set -g @dracula-plugins "weather"
set -g @tmux-weather-units "c"
set -g @dracula-show-fahrenheit false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top

set -gq allow-passthrough on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'   
